### ISSUE TITLE
How to use all features of opendronemap  from pyODM

### ISSUE THREAD

**Issue by bappaditya84** [OpenDroneMap/PyODM#14]
How to use functions like ndvi and all is not clear from the documentation of pyODM. Moreover, I want write python functions for activities shown in WebODM GUI. Can you help with that? The result contains a report in pdf format which includes many thing and I am not getting any idea how to compute them using pyODM. Please guide me in this. I want to utilize this api using python scripts.

**Comment by pierotofy** [comment]
Could we move this conversation over to the forum at https://community.opendronemap.org? :pray: The forum is the right place to ask questions (we try to keep the GitHub issue tracker for feature requests and bugs only). Thank you! :+1:
