### ISSUE TITLE
pyODM can not access NodeODM server

### ISSUE THREAD

**Issue by bappaditya-td** [OpenDroneMap/PyODM#15]
Initially it worked well. But suddenly pyodm can not communicate with NodeODM server. The server is running. NodeODM web console is working fine. pyodm stucked at create_task(). Can anyone help?

**Comment by pierotofy** [comment]
Could we move this conversation over to the forum at https://community.opendronemap.org? :pray: The forum is the right place to ask questions (we try to keep the GitHub issue tracker for feature requests and bugs only). Thank you! :+1:
