### ISSUE TITLE
Add smarter retry mechanism

### ISSUE THREAD

**Issue by pierotofy** [OpenDroneMap/PyODM#16]
Currently PyODM will retry to upload images to a node even if a critical error (e.g. a non-recoverable, non-network related error) happens (e.g. a user uploads more images than a node allows). This stalls the upload until all retries have been exhausted. We should differentiate between non-recoverable and recoverable error to change the upload retry logic.

**Comment by theoway** [comment]
@pierotofy  I've been using PyODM for quite some time, and I'd like to implement this functionality. Could you maybe provide some pointers to get started on it 😄

**Comment by pierotofy** [comment]
Hey @theoway :hand: you would need to start by identifying the lines that retry the upload when it fails.

Then you would need to change the logic to retry only on network-related errors. On top of my head, I'm not sure if this will require changes to the server (NodeODM) code too (it might).

Sorry I can't be more helpful, I haven't really digged into how to solve this one.

**Comment by theoway** [comment]
@pierotofy That ought to get me started. I'll do like you said. Will keep you posted! 😄

**Comment by theoway** [comment]
@pierotofy I've dug out the relevant code for our issue. `ODMError` is generic and all the other `Exceptions` derive from it. Now, my understanding is that whenever an exception occurs, it only enters the `ODMError` except block and if there are retries remaining, it will queue a new task. Now, it means even if a non-recoverable error occurs, it gonna queue a new task if there are retries left. 
To fix it, I would need to know what kind of error code does NodeODM return during the case of non-recoverable situation. That way, I'll add an additional check for that return code and perform the relevant steps to bypass the retry mechanism. 
I hope it makes sense. Waiting for your reply :)
https://github.com/OpenDroneMap/PyODM/blob/81b6d0d33d9aefe0c390c382908f7fb9edecbf2a/pyodm/api.py#L320-L331

Currently, it raises an exception despite the the kind of error(recoverable or non-recoverable)
https://github.com/OpenDroneMap/PyODM/blob/81b6d0d33d9aefe0c390c382908f7fb9edecbf2a/pyodm/api.py#L315-L319
If you could tell me more about non-recoverable _return codes_ returned by NodeODM, I can get it fixed... 💯

**Comment by pierotofy** [comment]
Thanks for the analysis, I think you're spot on. :pray: 

I think the core issue is in the NodeODM spec, we currently don't differentiate between recoverable/non-recoverable errors in NodeODM. I think a good approach to fix this is to expand the spec to do so.

By default all errors should be recoverable (trigger a retry logic, so keeping the current behavior unchanged); if an error is non-recoverable, the error response from NodeODM could be:

```
{ error: "message", noRetry: true }
```

Or something of that effect.

So I think this needs to be added to the NodeODM spec and in the relevant places within NodeODM (as a starting point, adding support for one error response with `noRetry` logic in NodeODM would be sufficient).

**Comment by theoway** [comment]
@pierotofy Just scanned **NodeODM**'s code. Here's what I think I would do to make this work:
We only need to add the `noRetry` to the response for this request endpoint.
```
app.post('/task/new/upload/:uuid', authCheck, taskNew.getUUID, taskNew.preUpload, taskNew.uploadImages, taskNew.handleUpload);
```
We can start out by adding `noRetry` in the error body returned by `handleUpload`, as the error occurs when there are no files passed and it seems to me an non-recoverable condition. User should not have to wait for the retries in this particular case.
```
    preUpload: (req, res, next) => {
        // Testing stuff
        if (!config.test) next();
        else{
            if (config.testDropUploads){
                if (Math.random() < 0.5) res.sendStatus(500);
                else next();
            }else{
                next();
            }
        }
    },


    uploadImages: upload.array("images"),


    handleUpload: (req, res) => {
        // IMPROVEMENT: check files count limits ahead of handleTaskNew
        if (req.files && req.files.length > 0){
            res.json({success: true});
        }else{
            res.json({error: "Need at least 1 file."});
        }
    },
```

I'll dig some more places where `noRetry` should be added. Waiting for your reply on this. If you give the green signal. I'll first make PR in _NodeODM_ then in _PyODM_.

**Comment by pierotofy** [comment]
Perfect :+1:
