### ISSUE TITLE
Distributed tasks via clusterodm and nodeodm

### ISSUE THREAD

**Issue by mindonm** [OpenDroneMap/PyODM#21]
There is an error happend When I distributed tasks via 1-clusterodm and 3-nodeodm by docker-compose on one machine(windows10) with code 'task.info()' as follow.
'pyodm.exceptions.NodeResponseError: Proxy redirect error: connect ETIMEDOUT ip:port'
But at that time tasks were still running.

**Comment by pierotofy** [comment]
Could we move this conversation over to the forum at https://community.opendronemap.org? :pray: The forum is the right place to ask questions (we try to keep the GitHub issue tracker for feature requests and bugs only). Thank you! :+1:

**Comment by mindonm** [comment]
Ok, just move it.
