### ISSUE TITLE
ClusterODM support? Advice on approaches

### ISSUE THREAD

**Issue by SteveCohen** [OpenDroneMap/PyODM#24]
Hi folks,
What level of interest is there in ClusterODM support?

I'm willing to do the initial development, and thought I'd share my thoughts/plans here for comment. 

I can see two approaches, which I'd like comment on: 

## Option 1: Use the ClusterODM REST API.
The current PyODM approach to calling REST apis could be  extended to the ClusterODM REST API (currently used in the ClusterODM web interface). This extends the current PyODM patterns which will keep the code cleaner and simpler; conveniently, I'm also familiar with this approach and it feels doable. 

## Option 2: Connect to the ClusterODM Telnet interface.
This is consistent with the (apparently-preferred?) ClusterODM interface patterns, as per it's [documentation](https://www.opendronemap.org/clusterodm/); also telnet looks like it might support  additional features (e.g. the "NODE BEST" command doesn't seem to be replicated in the REST API?) - is this true? The downside is Telnet is quite a different approach to the current PyODM/NodeODM REST approach, making the pyodm code more complicated to maintain.

I'm leaning toward option 1. Will make a start when I get a moment; in the meantime I thought I'd open up for comment!

Steve.

**Comment by pierotofy** [comment]
I think an interface that communicates with ClusterODM's admin features could be part of a separate repository/library (PyODM's goal is to speak with the NodeODM API)?

Would be a cool project to work on!
