### ISSUE TITLE
Link Task to WebODM

### ISSUE THREAD

**Issue by kikislater** [OpenDroneMap/PyODM#26]
Hi,

Is there a way to link a task sent through PyODM to WebODM ?

**Comment by pierotofy** [comment]
There's not; PyODM talks exclusively with the NodeODM API.

**Comment by kikislater** [comment]
but there is no python module talking to webodm ...

**Comment by pierotofy** [comment]
Some work had been started in https://github.com/OpenDroneMap/python-WebODM but was never finished.

**Comment by kikislater** [comment]
Ok forgot to read this: http://docs.webodm.org/#how-to-process-images
Sufficient for me, thanks. I have working example to batch process drone images with python to nodeodm from a Nextcloud storage
