### ISSUE TITLE
3D model is poor when with boundary constraints by pyodm 

### ISSUE THREAD

**Issue by meiyanzhao** [OpenDroneMap/PyODM#29]
When dealing with oblique photography models with boundary constraints, the output model effect is very poor, the model is very rough, with many small holes, texture mapping errors at the boundaries, and is messy(as shown in the first three images). But without boundary constraints(if this parameter is not set:"boundary":boundarystr), the effect of the central region of the model is still good(as shown in the last image）.
![1](https://github.com/OpenDroneMap/PyODM/assets/169761406/796c45ab-3048-4641-9d32-1cc0d861d37c)
![2](https://github.com/OpenDroneMap/PyODM/assets/169761406/fc5c6e87-4c27-413a-9d26-ca7b9a35c4c2)
![3](https://github.com/OpenDroneMap/PyODM/assets/169761406/9e08cd1f-947b-45db-b79f-d26691d45969)
![4](https://github.com/OpenDroneMap/PyODM/assets/169761406/a33c15d5-d252-4e61-8de5-37c7ed900434)

I did like this:
n = Node(ip, port)
task = n.create_task(images_name, {"3d-tiles": True,"boundary":boundarystr,"no-gpu":False})

Thank you very much for your guidance and assistance.

**Comment by pierotofy** [comment]
Could we move this conversation over to the forum at https://community.opendronemap.org? :pray: The forum is the right place to ask questions (we try to keep the GitHub issue tracker for feature requests and bugs only). Thank you! :+1:
