### ISSUE TITLE
Please create tag or release for package in distribution

### ISSUE THREAD

**Issue by kikislater** [OpenDroneMap/PyODM#33]
@pierotofy I have created an archlinux package as archlinux' based distribution doesn't allow pip anymore. 
Package from AUR (Arch user repository) is visible here : https://aur.archlinux.org/packages/python-pyodm

Btw I found that this repository doesn't have tag or release, on your next release to pypi, could please make a tag or release, it will then be easier to update package in linux distribution for example

**Comment by pierotofy** [comment]
Done!

**Comment by kikislater** [comment]
Thanks ! ;-)
